### ISSUE TITLE
Error: Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by christophechevalier** [Useful-Software-Solutions-Ltd/angular2-useful-swiper#22]
**Hi guys !**  

I found a critical error when using the scrollbar settings of the swiper config.

Let me explain :

I am on a page in which I defined a swipe. And some slides.
When I change my view, and if I resize my browser window, I get this error:
![selection_078](https://cloud.githubusercontent.com/assets/7148846/25493416/669b370a-2b76-11e7-8489-a0961c944f1c.png)

When I comment on everything about the scrollbar, I have no more error.

Is this an issue you know or is this a new bug?

**Minimal reproduction of the problem with instructions**
I try to illustrate my problem with an example code in [http://plnkr.co/edit/L1yZExueIxC6e201vnZu?p=preview](http://plnkr.co/edit/L1yZExueIxC6e201vnZu?p=preview)
but it's not working. The type of bundle is not the right one.

Could you show me a correct base to make you a demo of the bug encountered?
Related @JayChase @krjordan 

* **Angular version:** 4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7]

**Thank you.**

**Comment by JayChase** [comment]
I've created a demo plunk you can use for recreating issues: http://embed.plnkr.co/qM4jHG/

**Comment by ubaid-rehman** [comment]
same issue, no help available.
https://plnkr.co/edit/OyA5s3uMLDU2FW6K6x5V?p=preview

**Comment by ubaid-rehman** [comment]
Apparently 
If we add 
`      swiperConfig: SwiperOptions = {
    scrollbar:{
      container: ".swiper-scrollbar",
      hide: false,
      draggable: true,
      snapOnRelease: true
    }
};`

to swiper config, this issue appears.

I went on to debug, and find out that in swiper.js there is a "set" function in s.scrollbar and it is doing this

`var sb = s.scrollbar;
sb.track = $(s.params.scrollbar);`

so when scrollbar is an object, it throws this exception. My workaround is to provide selector in scrollbar like this 
  `swiperConfig: SwiperOptions = {
    scrollbar:".swiper-scrollbar"
};`

so it gets a selector instead of an object. Please let me know if you fix this, I would like to use scrollbar's other options. Cheers
